services:
  api:
    container_name: geoip_api
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GEOIPUPDATE_ACCOUNT_ID: ${GEOIPUPDATE_ACCOUNT_ID}
        GEOIPUPDATE_LICENSE_KEY: ${GEOIPUPDATE_LICENSE_KEY}
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./data:/usr/share/GeoIP
    restart: always

networks:
  default:
    driver: bridge
